### ISSUE TITLE
open issues

### ISSUE THREAD

**Issue by barmey** [Dubnov/BookNet#4]
מצרף קובץ עם הדברים הפתוחים שלנו.
מסומן בצהוב מה שעדיין לא בוצע.. חלק מהמשימות הפתוחות כבר חילקנו ביננו ועדין לא בוצעו וחלק עדין לא חילקנו מי עושה מה..
[ASP_MVC_2016 - Final Project Requirements.docx](https://github.com/Dubnov/BookNet/files/534700/ASP_MVC_2016.-.Final.Project.Requirements.docx)

**Comment by chengor** [comment]
[ASP_MVC_2016.-.Final.Project.Requirements (1).docx](https://github.com/Dubnov/BookNet/files/534709/ASP_MVC_2016.-.Final.Project.Requirements.1.docx)

**Comment by chengor** [comment]
הוספתי את הקובץ המעודכן לתיקייה הראשית בגיט, תעדכנו שם.
